### ISSUE TITLE
Unable to proceed past step 3 - cloning issue

### ISSUE THREAD

**Issue by tahirsoudagar** [tylerburleigh/nike-buy-bot#7]
Hi guys, sorry for posting a noob issue however I'm unable to proceed past the clone stage as typing 'git clone https://github.com/tylerburleigh/nike-buy-bot.git' in a command line isn't working, as it is saying its not recognised. Any possible solutions? I've installed GIT and node.

**Comment by sarthaktexas** [comment]
can you post a ss?

**Comment by tahirsoudagar** [comment]
I managed to fix the issue, thanks for the concern anyway.
